export type DestinationPackage = {
  name: string;
  duration: string;
  price: string;
  priceNote: string;
  inclusions: string[];
  tag?: string;
};

export type Destination = {
  slug: string;
  title: string;
  type: "domestic" | "international";
  heroImage: string;
  heroAlt: string;
  tagline: string;
  startPrice: string;
  popularDuration: string;
  tripsCount: string;
  visaNote?: string;
  highlights: { place: string; desc: string }[];
  packages: DestinationPackage[];
  faqs: { q: string; a: string }[];
  related: string[];
};

const D: Destination[] = [
  // ─── DOMESTIC ───────────────────────────────────────────────────────────────

  {
    slug: "kerala-tour-from-bangalore",
    title: "Kerala Tour Packages from Bangalore",
    type: "domestic",
    heroImage: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1600&q=85",
    heroAlt: "Kerala backwaters tour from Bangalore",
    tagline: "Munnar, Alleppey backwaters & Kovalam — starting ₹13,500 per person",
    startPrice: "₹13,500",
    popularDuration: "5N/6D",
    tripsCount: "500+",
    highlights: [
      { place: "Munnar", desc: "Tea plantations, Eravikulam National Park, Echo Point & cool hill-station climate." },
      { place: "Alleppey (Alappuzha)", desc: "Iconic houseboat stays, backwater cruises and golden sunset views." },
      { place: "Thekkady", desc: "Elephant safari inside Periyar Tiger Reserve, spice plantation tours." },
      { place: "Kovalam Beach", desc: "Crescent-shaped beaches, lighthouse views & Ayurvedic resorts." },
      { place: "Wayanad", desc: "Bamboo forests, Edakkal Caves, tribal culture & mist-covered valleys." },
      { place: "Kumarakom", desc: "Bird sanctuary, backwater resorts and serene fishing villages." },
    ],
    packages: [
      { name: "Budget Package", duration: "4N/5D", price: "₹13,500", priceNote: "per person, twin sharing", inclusions: ["Munnar 2N + Alleppey 2N", "AC accommodation", "Daily breakfast", "Sightseeing by AC cab", "Airport transfers"] },
      { name: "Family Package", duration: "5N/6D", price: "₹18,900", priceNote: "per person, twin sharing", inclusions: ["Munnar 2N + Alleppey 1N + Thekkady 2N", "3-star hotels", "Daily breakfast & dinner", "Elephant safari", "Houseboat half-day", "All transfers"], tag: "Most Popular" },
      { name: "Honeymoon Package", duration: "5N/6D", price: "₹22,500", priceNote: "per couple", inclusions: ["Munnar 2N + Alleppey houseboat 1N + Kovalam 2N", "4-star resorts", "Candlelight dinner", "Couples spa", "Private cab", "Flower decoration"], tag: "Best for Couples" },
    ],
    faqs: [
      { q: "How far is Kerala from Bangalore?", a: "Bangalore to Munnar is ~460 km (9 hrs by road). By flight, Kochi airport is under 1.5 hours. Most packages operate from Kochi." },
      { q: "Best time to visit Kerala from Bangalore?", a: "October–March is ideal — pleasant weather. July–September is monsoon (great for Ayurveda). April–June is warm but manageable." },
      { q: "Is Kerala good for a honeymoon trip?", a: "Yes — Alleppey houseboat, Munnar hill stations, Kovalam beach resorts. Our honeymoon package covers all the best romantic spots." },
      { q: "Cost of Kerala trip from Bangalore for 2?", a: "Budget 4N/5D for 2 starts ₹27,000. Honeymoon packages for 2 range ₹36,000–₹55,000 depending on hotels." },
    ],
    related: ["goa-tour-from-bangalore", "andaman-tour-from-bangalore", "honeymoon-packages-from-bangalore"],
  },

  {
    slug: "goa-tour-from-bangalore",
    title: "Goa Tour Packages from Bangalore",
    type: "domestic",
    heroImage: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1600&q=85",
    heroAlt: "Goa beach tour packages from Bangalore",
    tagline: "North & South Goa beaches, water sports & casinos — from ₹5,500",
    startPrice: "₹5,500",
    popularDuration: "3N/4D",
    tripsCount: "600+",
    highlights: [
      { place: "Calangute & Baga", desc: "North Goa's most popular beaches with shacks, water sports and vibrant nightlife." },
      { place: "Anjuna & Arambol", desc: "Hippie flea market, laid-back beach vibes and sunrise parties." },
      { place: "Old Goa Churches", desc: "UNESCO World Heritage — Basilica of Bom Jesus, Se Cathedral." },
      { place: "Dudhsagar Waterfalls", desc: "One of India's tallest waterfalls — spectacular jeep safari post-monsoon." },
      { place: "South Goa Beaches", desc: "Colva, Palolem & Cavelossim — quieter, cleaner, family-friendly." },
      { place: "Spice Plantations", desc: "Guided spice farm tours with traditional Goan lunch." },
    ],
    packages: [
      { name: "Budget Package", duration: "3N/4D", price: "₹5,500", priceNote: "per person, twin sharing", inclusions: ["North Goa sightseeing", "AC guesthouse", "Daily breakfast", "Sightseeing cab", "Station/airport transfers"] },
      { name: "Standard Package", duration: "4N/5D", price: "₹9,500", priceNote: "per person, twin sharing", inclusions: ["North + South Goa", "3-star beach resort", "Breakfast & 2 dinners", "Water sports", "Dudhsagar jeep safari", "AC cab"], tag: "Most Popular" },
      { name: "Premium Package", duration: "5N/6D", price: "₹14,500", priceNote: "per person, twin sharing", inclusions: ["North + South Goa", "4-star beachfront resort", "All meals", "Casino entry", "Sunset cruise", "Spice plantation tour", "Private cab"] },
    ],
    faqs: [
      { q: "How to reach Goa from Bangalore?", a: "Train: 9–12 hrs (scenic Konkan route). Road: ~600 km via NH48 (9–10 hrs). Flight: 1.5 hrs with multiple daily flights. All transfers included in our packages." },
      { q: "Best time to visit Goa from Bangalore?", a: "November–February (peak — best weather). October & March (shoulder — fewer crowds). Avoid May–June for beach trips." },
      { q: "Can I do Goa in 3 days from Bangalore?", a: "Yes — a long weekend (Fri–Mon) covers North Goa well. For North + South Goa + Dudhsagar, take 5 days." },
    ],
    related: ["kerala-tour-from-bangalore", "coorg-ooty-tour-from-bangalore", "andaman-tour-from-bangalore"],
  },

  {
    slug: "kashmir-tour-from-bangalore",
    title: "Kashmir Tour Packages from Bangalore",
    type: "domestic",
    heroImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1600&q=85",
    heroAlt: "Kashmir tour from Bangalore — Dal Lake houseboat",
    tagline: "Srinagar, Gulmarg, Pahalgam & Dal Lake houseboat — from ₹28,900",
    startPrice: "₹28,900",
    popularDuration: "5N/6D",
    tripsCount: "300+",
    highlights: [
      { place: "Srinagar", desc: "Dal Lake shikara rides, Mughal gardens (Nishat, Shalimar), Hazratbal Shrine." },
      { place: "Gulmarg", desc: "Asia's highest gondola ride, skiing in winter, green meadows in summer." },
      { place: "Pahalgam", desc: "Betaab Valley, Aru Valley, mini-Switzerland views & horse riding." },
      { place: "Sonmarg", desc: "Gateway to glaciers — Thajiwas Glacier, Vishansar Lake trek." },
      { place: "Dal Lake Houseboat", desc: "Stay on traditional wooden houseboat — Kashmir's most iconic experience." },
      { place: "Doodhpathri", desc: "Hidden meadow paradise — lush green carpets and wildflowers." },
    ],
    packages: [
      { name: "Standard (Without Flight)", duration: "5N/6D", price: "₹28,900", priceNote: "per person, twin sharing", inclusions: ["Srinagar 3N + Gulmarg 1N + Pahalgam 1N", "3-star + 1N houseboat", "Breakfast & dinner", "Sightseeing by tempo traveller", "Airport transfers"] },
      { name: "Premium Package", duration: "6N/7D", price: "₹42,500", priceNote: "per person, twin sharing", inclusions: ["Srinagar 3N + Gulmarg 2N + Pahalgam 1N", "4-star + premium houseboat", "All meals", "Gondola ride Phase 1 & 2", "Shikara + pony ride", "Private cab"], tag: "Best Experience" },
      { name: "With Flights", duration: "5N/6D", price: "₹42,000", priceNote: "per person, incl. BLR–SXR flights", inclusions: ["Bangalore–Srinagar–Bangalore flights", "3-star + houseboat", "Breakfast & dinner", "Gulmarg & Pahalgam", "Shikara ride", "All transfers"], tag: "Most Convenient" },
    ],
    faqs: [
      { q: "Is it safe to travel to Kashmir from Bangalore?", a: "Yes — Srinagar, Gulmarg, Pahalgam tourist circuit is safe. We monitor ground conditions daily and brief customers before departure." },
      { q: "Best time to visit Kashmir from Bangalore?", a: "March–June: spring/summer, cherry blossoms. Dec–Feb: snow in Gulmarg for skiing. Sep–Nov: autumn chinar trees turn red." },
      { q: "How to fly to Kashmir from Bangalore?", a: "Bengaluru (BLR) to Srinagar (SXR) — ~2.5 hours. Direct and 1-stop flights available. We arrange all transfers." },
    ],
    related: ["shimla-manali-tour-from-bangalore", "leh-ladakh-tour-from-bangalore", "honeymoon-packages-from-bangalore"],
  },

  {
    slug: "shimla-manali-tour-from-bangalore",
    title: "Shimla Manali Tour Packages from Bangalore",
    type: "domestic",
    heroImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1600&q=85",
    heroAlt: "Shimla Manali tour from Bangalore — Himachal Pradesh snow mountains",
    tagline: "Shimla hill station, Manali snow & Rohtang Pass — from ₹15,999",
    startPrice: "₹15,999",
    popularDuration: "6N/7D",
    tripsCount: "400+",
    highlights: [
      { place: "Shimla", desc: "British-era Mall Road, Christ Church, Kufri & toy train ride through mountains." },
      { place: "Manali", desc: "Solang Valley snow, Rohtang Pass, Hadimba Temple & Old Manali cafes." },
      { place: "Rohtang Pass", desc: "Snow point at 3,978 m — only accessible May–October. Jeep safari from Manali." },
      { place: "Kullu", desc: "Beas river rafting, Kullu Shawl market, Bijli Mahadev temple." },
      { place: "Solang Valley", desc: "Adventure hub — skiing (winter), zorbing, paragliding & cable car." },
      { place: "Kasol & Kheerganga", desc: "Mini-Israel of India — backpacker cafes, Parvati Valley trek." },
    ],
    packages: [
      { name: "Shimla-Manali Budget", duration: "6N/7D", price: "₹15,999", priceNote: "per person, twin sharing", inclusions: ["Shimla 3N + Manali 3N", "AC hotels", "Daily breakfast", "Sightseeing by AC cab", "Volvo bus transfers"] },
      { name: "Shimla-Manali Deluxe", duration: "7N/8D", price: "₹22,500", priceNote: "per person, twin sharing", inclusions: ["Shimla 3N + Manali 4N", "3-star hotels", "Breakfast & dinner", "Rohtang Pass jeep", "Solang Valley activities", "Private cab"], tag: "Most Popular" },
      { name: "Honeymoon Special", duration: "6N/7D", price: "₹28,000", priceNote: "per couple", inclusions: ["Shimla 3N + Manali 3N", "Resort with valley views", "All meals", "Candlelight dinner", "Rohtang jeep", "Snow activities"], tag: "Best for Couples" },
    ],
    faqs: [
      { q: "Best time to visit Shimla Manali from Bangalore?", a: "April–June: summer, pleasant and accessible. December–February: heavy snow, Rohtang closed but Solang Valley skiing is great. Avoid July–August monsoon for Manali." },
      { q: "How to reach Shimla Manali from Bangalore?", a: "Fly Bengaluru to Chandigarh or Delhi, then cab to Shimla (3 hrs from Chandigarh) or Manali (7 hrs from Delhi/Chandigarh). We arrange all intercity transfers." },
    ],
    related: ["kashmir-tour-from-bangalore", "leh-ladakh-tour-from-bangalore", "uttarakhand-tour-from-bangalore"],
  },

  {
    slug: "andaman-tour-from-bangalore",
    title: "Andaman Tour Packages from Bangalore",
    type: "domestic",
    heroImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&q=85",
    heroAlt: "Andaman Nicobar Islands tour from Bangalore — Havelock Island beach",
    tagline: "Port Blair, Havelock Island & Neil Island — from ₹18,500",
    startPrice: "₹18,500",
    popularDuration: "5N/6D",
    tripsCount: "250+",
    highlights: [
      { place: "Port Blair", desc: "Cellular Jail light-and-sound show, Corbyn's Cove Beach, Ross Island." },
      { place: "Havelock Island (Swaraj Dweep)", desc: "Radhanagar Beach — Asia's best beach, scuba diving at Elephant Beach." },
      { place: "Neil Island (Shaheed Dweep)", desc: "Bharatpur Beach, Lakshamanpur beach, natural rock arch — peaceful & uncrowded." },
      { place: "Baratang Island", desc: "Limestone caves, mangrove creek safari & mud volcanoes." },
      { place: "Scuba Diving", desc: "World-class coral reefs — beginner & PADI certified dive spots." },
      { place: "Sea Walk", desc: "Underwater walk with helmet — no swimming experience required." },
    ],
    packages: [
      { name: "Andaman Standard", duration: "5N/6D", price: "₹18,500", priceNote: "per person, twin sharing", inclusions: ["Port Blair 3N + Havelock 2N", "3-star hotels", "Daily breakfast", "Cellular Jail visit", "Ferry transfers", "Airport pick-up"] },
      { name: "Andaman with Scuba", duration: "6N/7D", price: "₹25,900", priceNote: "per person, twin sharing", inclusions: ["Port Blair 2N + Havelock 3N + Neil 1N", "Beach resort", "Breakfast & dinner", "Scuba diving (2 dives)", "Sea walk", "Glass-bottom boat"], tag: "Most Popular" },
      { name: "Andaman Premium", duration: "7N/8D", price: "₹34,500", priceNote: "per couple", inclusions: ["All islands covered", "4-star & beach resort", "All meals", "Scuba + sea walk + snorkelling", "Baratang island trip", "Private speedboat", "Couple photos"], tag: "Best Experience" },
    ],
    faqs: [
      { q: "How to reach Andaman from Bangalore?", a: "Fly Bengaluru (BLR) to Port Blair (IXZ) — ~2.5 hrs, daily direct and 1-stop flights. We include flight booking in our packages." },
      { q: "Best time to visit Andaman from Bangalore?", a: "October–May is ideal. December–February is peak season — perfect weather. June–September is monsoon, some activities restricted." },
      { q: "Is Andaman good for a honeymoon from Bangalore?", a: "Yes — stunning beaches, water sports, private resorts and scenic island hopping make Andaman one of India's best honeymoon spots." },
    ],
    related: ["kerala-tour-from-bangalore", "goa-tour-from-bangalore", "honeymoon-packages-from-bangalore"],
  },

  {
    slug: "coorg-ooty-tour-from-bangalore",
    title: "Coorg & Ooty Tour Packages from Bangalore",
    type: "domestic",
    heroImage: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=1600&q=85",
    heroAlt: "Coorg coffee estate tour from Bangalore — weekend getaway",
    tagline: "Coorg coffee estates & Ooty Nilgiris — weekend getaways from ₹4,500",
    startPrice: "₹4,500",
    popularDuration: "2N/3D",
    tripsCount: "800+",
    highlights: [
      { place: "Coorg (Kodagu)", desc: "Coffee & spice estates, Abbey Falls, Raja's Seat, Dubare Elephant Camp." },
      { place: "Ooty (Udhagamandalam)", desc: "Botanical Gardens, Doddabetta Peak, Ooty Lake boat ride & toy train." },
      { place: "Wayanad", desc: "Bamboo forest, Chembra Peak trek, Edakkal Caves & tribal villages." },
      { place: "Kodaikanal", desc: "Coaker's Walk, Pillar Rocks, Bryant Park, Silver Cascade Falls." },
      { place: "Munnar", desc: "Tea plantation walks, Top Station viewpoint, elephant sightings." },
      { place: "Coonoor", desc: "Lamb's Rock, Dolphin's Nose, Sim's Park & quieter than Ooty." },
    ],
    packages: [
      { name: "Coorg Weekend", duration: "2N/3D", price: "₹4,500", priceNote: "per person, twin sharing", inclusions: ["Coorg resort 2N", "Daily breakfast", "Coffee estate tour", "Abbey Falls & Raja's Seat", "AC cab from Bangalore"] },
      { name: "Ooty Weekend", duration: "2N/3D", price: "₹4,999", priceNote: "per person, twin sharing", inclusions: ["Ooty hotel 2N", "Daily breakfast", "Botanical Gardens, Doddabetta", "Toy train ride", "AC cab from Bangalore"] },
      { name: "Coorg + Ooty Combo", duration: "4N/5D", price: "₹9,500", priceNote: "per person, twin sharing", inclusions: ["Coorg 2N + Ooty 2N", "3-star resorts", "Breakfast & dinner", "All sightseeing", "AC cab throughout"], tag: "Best Value" },
    ],
    faqs: [
      { q: "How far is Coorg from Bangalore?", a: "Coorg (Madikeri) is ~265 km from Bangalore — about 5 hours by road. Ooty is ~295 km — 6 hours. Both are popular weekend trips." },
      { q: "Best time to visit Coorg and Ooty from Bangalore?", a: "October–March is best — cool and clear. April–June is warm but still pleasant. July–September is monsoon — lush green but can be rainy." },
    ],
    related: ["kerala-tour-from-bangalore", "wayanad-tour-from-bangalore", "goa-tour-from-bangalore"],
  },

  {
    slug: "rajasthan-tour-from-bangalore",
    title: "Rajasthan Tour Packages from Bangalore",
    type: "domestic",
    heroImage: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=1600&q=85",
    heroAlt: "Rajasthan Jaipur Hawa Mahal tour from Bangalore",
    tagline: "Jaipur, Udaipur, Jaisalmer & Jodhpur — Royal Rajasthan from ₹19,000",
    startPrice: "₹19,000",
    popularDuration: "6N/7D",
    tripsCount: "350+",
    highlights: [
      { place: "Jaipur (Pink City)", desc: "Amber Fort, Hawa Mahal, City Palace, Jantar Mantar & local bazaars." },
      { place: "Udaipur (City of Lakes)", desc: "Lake Pichola, City Palace, Jag Mandir, Saheliyon Ki Bari." },
      { place: "Jaisalmer (Golden City)", desc: "Desert fort, Sam Sand Dunes camel safari & tented stays." },
      { place: "Jodhpur (Blue City)", desc: "Mehrangarh Fort, blue-painted old city, Umaid Bhawan Palace." },
      { place: "Pushkar", desc: "Sacred Pushkar Lake, Brahma Temple, camel fair (November)." },
      { place: "Ranthambore", desc: "Tiger reserve — one of India's best for tiger sightings." },
    ],
    packages: [
      { name: "Jaipur-Udaipur", duration: "5N/6D", price: "₹19,000", priceNote: "per person, twin sharing", inclusions: ["Jaipur 3N + Udaipur 2N", "Heritage hotels", "Daily breakfast", "Amber Fort, Lake Pichola", "AC cab from Delhi/Jaipur airport"] },
      { name: "Royal Rajasthan", duration: "7N/8D", price: "₹28,500", priceNote: "per person, twin sharing", inclusions: ["Jaipur 2N + Jodhpur 2N + Jaisalmer 2N + Udaipur 1N", "3-star hotels", "Breakfast & dinner", "Desert safari", "Camel ride", "All transfers"], tag: "Most Popular" },
      { name: "Rajasthan with Flight", duration: "6N/7D", price: "₹34,000", priceNote: "per person, incl. BLR–Jaipur flight", inclusions: ["Bangalore → Jaipur flight", "Jaipur 2N + Udaipur 2N + Jodhpur 2N", "3-star hotels", "All meals", "Private cab", "All sightseeing"], tag: "Most Convenient" },
    ],
    faqs: [
      { q: "Best time to visit Rajasthan from Bangalore?", a: "October–March is ideal — cool, perfect for desert camps. Avoid April–June (extreme heat 40–48°C). October's Pushkar Camel Fair is a unique experience." },
      { q: "How to reach Rajasthan from Bangalore?", a: "Fly Bengaluru to Jaipur (BLR–JAI, ~2 hrs). Alternatively fly to Delhi and road trip through Rajasthan. We arrange complete transfers." },
    ],
    related: ["kashmir-tour-from-bangalore", "golden-triangle-tour-from-bangalore", "honeymoon-packages-from-bangalore"],
  },

  {
    slug: "uttarakhand-tour-from-bangalore",
    title: "Uttarakhand Tour Packages from Bangalore",
    type: "domestic",
    heroImage: "https://images.unsplash.com/photo-1585016495481-91613b765ee7?w=1600&q=85",
    heroAlt: "Uttarakhand Rishikesh Haridwar tour from Bangalore",
    tagline: "Rishikesh, Haridwar, Nainital & Mussoorie — from ₹14,500",
    startPrice: "₹14,500",
    popularDuration: "5N/6D",
    tripsCount: "200+",
    highlights: [
      { place: "Rishikesh", desc: "River rafting, yoga ashrams, Laxman Jhula, Beatles Ashram & bungee jumping." },
      { place: "Haridwar", desc: "Har Ki Pauri Ganga aarti — one of India's most spiritual experiences." },
      { place: "Nainital", desc: "Naini Lake boat ride, Mall Road, Snow View Point & Zoo." },
      { place: "Mussoorie (Queen of Hills)", desc: "Kempty Falls, Gun Hill cable car, Company Garden & Mall Road." },
      { place: "Auli", desc: "India's best skiing destination — panoramic Himalayan glacier views." },
      { place: "Chopta-Tungnath", desc: "Mini Switzerland of India — highest Shiva temple & Chandrashila trek." },
    ],
    packages: [
      { name: "Rishikesh-Haridwar", duration: "3N/4D", price: "₹9,500", priceNote: "per person, twin sharing", inclusions: ["Rishikesh 2N + Haridwar 1N", "Hotel + ashram stay option", "Breakfast", "River rafting", "Ganga aarti", "Airport transfers"] },
      { name: "Uttarakhand Highlights", duration: "5N/6D", price: "₹14,500", priceNote: "per person, twin sharing", inclusions: ["Haridwar 1N + Rishikesh 2N + Mussoorie 2N", "3-star hotels", "Breakfast & dinner", "Kempty Falls, Laxman Jhula", "AC cab throughout"], tag: "Most Popular" },
      { name: "Char Dham Yatra", duration: "10N/11D", price: "₹32,000", priceNote: "per person, twin sharing", inclusions: ["Yamunotri, Gangotri, Kedarnath, Badrinath", "Accommodation throughout", "All meals", "Helicopter option available", "Expert guide", "AC cab"] },
    ],
    faqs: [
      { q: "Best time to visit Uttarakhand from Bangalore?", a: "March–June (summer) is ideal for most places. Char Dham opens May–November. December–February is cold & snowy — good for Auli skiing." },
      { q: "How to reach Uttarakhand from Bangalore?", a: "Fly Bengaluru to Dehradun (DED) or Delhi, then road to destinations. Dehradun airport is 30 mins from Rishikesh, 55 mins from Mussoorie." },
    ],
    related: ["kashmir-tour-from-bangalore", "shimla-manali-tour-from-bangalore", "leh-ladakh-tour-from-bangalore"],
  },

  {
    slug: "leh-ladakh-tour-from-bangalore",
    title: "Leh Ladakh Tour Packages from Bangalore",
    type: "domestic",
    heroImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1600&q=85",
    heroAlt: "Leh Ladakh tour from Bangalore — Pangong Lake",
    tagline: "Pangong Lake, Nubra Valley, Magnetic Hill — from ₹24,500",
    startPrice: "₹24,500",
    popularDuration: "6N/7D",
    tripsCount: "150+",
    highlights: [
      { place: "Pangong Tso Lake", desc: "The iconic blue-green lake stretching into Tibet — unforgettable sunrise & sunset." },
      { place: "Nubra Valley", desc: "Double-humped Bactrian camels, Diskit Monastery & sand dunes at 3,000 m." },
      { place: "Khardung La Pass", desc: "One of the world's highest motorable roads at 5,359 m — breathtaking views." },
      { place: "Magnetic Hill", desc: "Optical illusion hill where vehicles appear to roll uphill." },
      { place: "Leh Palace & Monasteries", desc: "Thiksey, Hemis, Alchi — ancient Buddhist monasteries in dramatic landscapes." },
      { place: "Tso Moriri Lake", desc: "Remote high-altitude lake at 4,522 m — less visited, more pristine." },
    ],
    packages: [
      { name: "Leh Ladakh Standard", duration: "6N/7D", price: "₹24,500", priceNote: "per person, twin sharing (without flight)", inclusions: ["Leh city 3N + Nubra 1N + Pangong 1N + Leh 1N", "Guesthouses & camps", "Breakfast & dinner", "Inner line permits", "Shared cab sightseeing"] },
      { name: "Leh Ladakh Premium", duration: "7N/8D", price: "₹34,000", priceNote: "per person, twin sharing (without flight)", inclusions: ["All main attractions + Tso Moriri", "3-star & luxury tents", "All meals", "Private cab", "Permits", "Acclimatisation day"], tag: "Best Experience" },
      { name: "Leh with Flights", duration: "6N/7D", price: "₹39,500", priceNote: "per person, incl. BLR–IXL flights", inclusions: ["Bangalore–Leh–Bangalore flights", "3-night hotel + camps", "All meals", "Pangong, Nubra", "Inner line permits", "All transfers"], tag: "Most Convenient" },
    ],
    faqs: [
      { q: "Best time to visit Leh Ladakh from Bangalore?", a: "June–September is the only accessible time for road trips. July–August (peak season) all roads are open. Fly for May/September shoulder months." },
      { q: "Do we need inner line permits for Ladakh?", a: "Yes — Pangong, Nubra Valley and some other areas require permits for Indian nationals. We arrange all required permits as part of the package." },
    ],
    related: ["kashmir-tour-from-bangalore", "shimla-manali-tour-from-bangalore", "uttarakhand-tour-from-bangalore"],
  },

  {
    slug: "golden-triangle-tour-from-bangalore",
    title: "Golden Triangle Tour Packages from Bangalore",
    type: "domestic",
    heroImage: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=1600&q=85",
    heroAlt: "Golden Triangle Delhi Agra Jaipur tour from Bangalore — Taj Mahal",
    tagline: "Delhi, Agra & Jaipur — India's iconic Golden Triangle from ₹16,500",
    startPrice: "₹16,500",
    popularDuration: "5N/6D",
    tripsCount: "300+",
    highlights: [
      { place: "Delhi", desc: "Qutub Minar, India Gate, Red Fort, Humayun's Tomb & Chandni Chowk street food." },
      { place: "Agra — Taj Mahal", desc: "UNESCO World Heritage Site — the world's greatest monument to love." },
      { place: "Agra Fort", desc: "Massive Mughal fort with views of the Taj Mahal from its towers." },
      { place: "Jaipur — Amber Fort", desc: "Majestic hilltop fort with elephant rides, mirror palace & stunning views." },
      { place: "Jaipur City Palace", desc: "Royal palace complex still partly home to the royal family of Jaipur." },
      { place: "Fatehpur Sikri", desc: "UNESCO Heritage — Akbar's abandoned Mughal capital between Agra and Jaipur." },
    ],
    packages: [
      { name: "Golden Triangle Classic", duration: "5N/6D", price: "₹16,500", priceNote: "per person, twin sharing", inclusions: ["Delhi 2N + Agra 1N + Jaipur 2N", "3-star hotels", "Daily breakfast", "All sightseeing by AC cab", "Delhi airport pickup/drop"] },
      { name: "Golden Triangle Deluxe", duration: "6N/7D", price: "₹24,000", priceNote: "per person, twin sharing", inclusions: ["Delhi 2N + Agra 2N + Jaipur 2N", "4-star hotels", "Breakfast & dinner", "Taj Mahal sunrise visit", "Amber Fort elephant ride", "Private cab"], tag: "Most Popular" },
      { name: "With Flight from Bangalore", duration: "5N/6D", price: "₹28,500", priceNote: "per person, incl. BLR–DEL flight", inclusions: ["Bangalore → Delhi flight", "Hotel + tours", "Breakfast", "All sightseeing", "Delhi–Jaipur–Delhi transfers"], tag: "Most Convenient" },
    ],
    faqs: [
      { q: "Best time for Golden Triangle tour from Bangalore?", a: "October–March is perfect — cool weather in Delhi, Agra and Jaipur. Avoid April–June (extreme heat). July–September is monsoon with occasional flooding." },
      { q: "Can I see the Taj Mahal at sunrise?", a: "Yes — our Deluxe package includes a special sunrise visit to the Taj Mahal, the most magical time to experience it with fewer crowds and beautiful morning light." },
    ],
    related: ["rajasthan-tour-from-bangalore", "varanasi-tour-from-bangalore", "kashmir-tour-from-bangalore"],
  },

  {
    slug: "varanasi-tour-from-bangalore",
    title: "Varanasi Tour Packages from Bangalore",
    type: "domestic",
    heroImage: "https://images.unsplash.com/photo-1561361058-c24e71f7b944?w=1600&q=85",
    heroAlt: "Varanasi Ganga Aarti tour from Bangalore",
    tagline: "Ganga Aarti, ancient ghats & Sarnath — spiritual Varanasi from ₹11,500",
    startPrice: "₹11,500",
    popularDuration: "3N/4D",
    tripsCount: "180+",
    highlights: [
      { place: "Ganga Aarti at Dashashwamedh Ghat", desc: "India's most spectacular evening prayer ritual on the banks of the Ganges." },
      { place: "Boat Ride at Sunrise", desc: "Early morning row past the ghats — one of the most moving experiences in India." },
      { place: "Kashi Vishwanath Temple", desc: "One of the 12 Jyotirlingas — one of Hinduism's most sacred Shiva temples." },
      { place: "Sarnath", desc: "Where Buddha gave his first sermon — Dhamek Stupa & Ashoka Pillar (10 km from Varanasi)." },
      { place: "Banaras Silk Bazaar", desc: "Shop for authentic Banarasi silk sarees and traditional textiles." },
      { place: "Street Food Walk", desc: "Kachori sabzi, thandai, chaat and the famous Banarasi paan." },
    ],
    packages: [
      { name: "Varanasi Weekend", duration: "2N/3D", price: "₹7,500", priceNote: "per person, twin sharing", inclusions: ["Varanasi hotel 2N", "Daily breakfast", "Boat ride at sunrise", "Evening Ganga aarti", "Kashi Vishwanath", "Airport transfers"] },
      { name: "Varanasi + Sarnath", duration: "3N/4D", price: "₹11,500", priceNote: "per person, twin sharing", inclusions: ["Varanasi hotel 3N", "Breakfast & dinner", "Sunrise boat ride", "Sarnath Buddhist tour", "All major ghats", "Banarasi silk shopping", "Transfers"], tag: "Most Popular" },
      { name: "With Flight from Bangalore", duration: "3N/4D", price: "₹18,500", priceNote: "per person, incl. BLR–VNS flight", inclusions: ["Bangalore–Varanasi–Bangalore flights", "3-star hotel", "All sightseeing", "Ganga aarti front seats", "Private cab"] },
    ],
    faqs: [
      { q: "Best time to visit Varanasi from Bangalore?", a: "October–March is ideal. Dev Deepawali (November full moon) — 1 million lamps on the ghats — is the most spectacular time to visit." },
      { q: "How to reach Varanasi from Bangalore?", a: "Fly Bengaluru to Varanasi (BLR–VNS) — ~2–3 hours with 1 stop. Direct trains are also available (long journey). We include flight or train booking." },
    ],
    related: ["golden-triangle-tour-from-bangalore", "rajasthan-tour-from-bangalore", "uttarakhand-tour-from-bangalore"],
  },

  {
    slug: "chikmagalur-tour-from-bangalore",
    title: "Chikmagalur Tour Packages from Bangalore",
    type: "domestic",
    heroImage: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=1600&q=85",
    heroAlt: "Chikmagalur coffee plantation weekend trip from Bangalore",
    tagline: "Coffee plantations, Mullayanagiri & Bhadra Wildlife Sanctuary — from ₹3,500",
    startPrice: "₹3,500",
    popularDuration: "2N/3D",
    tripsCount: "500+",
    highlights: [
      { place: "Mullayanagiri", desc: "Highest peak in Karnataka at 1,930 m — trekking, sunrise views & cloud forests." },
      { place: "Coffee Estates", desc: "Walk through aromatic coffee and spice plantations with guided estate tours." },
      { place: "Bhadra Wildlife Sanctuary", desc: "Tiger reserve with jeep safaris — leopard, elephant, deer sightings." },
      { place: "Hebbe Falls", desc: "Stunning 168-metre waterfall accessible by jeep through coffee estates." },
      { place: "Kudremukh", desc: "Shola forests, meadows and challenging trekking near Chikmagalur." },
      { place: "Kemmanagundi", desc: "Z-Point viewpoint, Hebbe falls trek & serene hill station atmosphere." },
    ],
    packages: [
      { name: "Chikmagalur Weekend", duration: "2N/3D", price: "₹3,500", priceNote: "per person, twin sharing", inclusions: ["Homestay/resort 2N", "Daily breakfast", "Coffee estate tour", "Mullayanagiri & Z-Point", "AC cab from Bangalore"] },
      { name: "Chikmagalur Explorer", duration: "3N/4D", price: "₹6,500", priceNote: "per person, twin sharing", inclusions: ["Coffee estate stay 3N", "Breakfast & dinner", "Bhadra jeep safari", "Hebbe Falls jeep ride", "Mullayanagiri trek", "All local transfers"], tag: "Most Popular" },
    ],
    faqs: [
      { q: "How far is Chikmagalur from Bangalore?", a: "Chikmagalur is ~245 km from Bangalore — approximately 4.5 hours by road via Hassan. It's one of the most accessible weekend getaways from Bengaluru." },
    ],
    related: ["coorg-ooty-tour-from-bangalore", "wayanad-tour-from-bangalore", "kerala-tour-from-bangalore"],
  },

  {
    slug: "wayanad-tour-from-bangalore",
    title: "Wayanad Tour Packages from Bangalore",
    type: "domestic",
    heroImage: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=1600&q=85",
    heroAlt: "Wayanad Kerala forest tour from Bangalore",
    tagline: "Bamboo forests, wildlife & Edakkal Caves — from ₹5,500",
    startPrice: "₹5,500",
    popularDuration: "2N/3D",
    tripsCount: "350+",
    highlights: [
      { place: "Edakkal Caves", desc: "Ancient cave with Neolithic petroglyphs — prehistoric rock carvings at 1,200 m." },
      { place: "Chembra Peak", desc: "Wayanad's highest peak with a heart-shaped lake near the summit — great trek." },
      { place: "Wayanad Wildlife Sanctuary", desc: "Jeep safaris with elephant, tiger, gaur and deer sightings." },
      { place: "Soochipara & Meenmutty Falls", desc: "Stunning cascades through dense forest — accessible by trekking." },
      { place: "Bamboo Forest", desc: "Dense bamboo groves near Vythiri — peaceful walks and photography." },
      { place: "Thirunelli Temple", desc: "Ancient Vishnu temple in the forest — spiritual and serene setting." },
    ],
    packages: [
      { name: "Wayanad Budget", duration: "2N/3D", price: "₹5,500", priceNote: "per person, twin sharing", inclusions: ["Forest resort 2N", "Daily breakfast", "Edakkal Caves", "Soochipara Falls", "AC cab from Bangalore"] },
      { name: "Wayanad Explorer", duration: "3N/4D", price: "₹9,500", priceNote: "per person, twin sharing", inclusions: ["Treehouse/resort 3N", "Breakfast & dinner", "Wildlife safari", "Chembra Peak trek", "Waterfalls & caves", "Bamboo forest walk"], tag: "Most Popular" },
    ],
    faqs: [
      { q: "How far is Wayanad from Bangalore?", a: "Wayanad is ~280 km from Bangalore — approximately 5.5 hours via NH275. The drive itself through the Nilgiris Biosphere Reserve is scenic." },
    ],
    related: ["coorg-ooty-tour-from-bangalore", "kerala-tour-from-bangalore", "chikmagalur-tour-from-bangalore"],
  },

  {
    slug: "hampi-tour-from-bangalore",
    title: "Hampi Tour Packages from Bangalore",
    type: "domestic",
    heroImage: "https://images.unsplash.com/photo-1582487555893-9d2e7a64cf14?w=1600&q=85",
    heroAlt: "Hampi ruins Vijayanagara Empire tour from Bangalore",
    tagline: "Vijayanagara ruins, boulder landscapes & Tungabhadra — from ₹3,999",
    startPrice: "₹3,999",
    popularDuration: "2N/3D",
    tripsCount: "400+",
    highlights: [
      { place: "Virupaksha Temple", desc: "9th-century temple still active — the spiritual heart of Hampi." },
      { place: "Vittala Temple & Stone Chariot", desc: "UNESCO Heritage — famous musical pillars and iconic stone chariot." },
      { place: "Hemakuta Hill", desc: "Sunrise over Hampi's boulders — best photography spot in Karnataka." },
      { place: "Tungabhadra River", desc: "Coracle boat rides through giant granite boulders — unique experience." },
      { place: "Elephant Stables", desc: "11 domed chambers of the Vijayanagara royal elephant quarters." },
      { place: "Anjaneya Hill (Monkey Temple)", desc: "Birthplace of Hanuman — 570-step climb for panoramic sunrise views." },
    ],
    packages: [
      { name: "Hampi Weekend", duration: "2N/3D", price: "₹3,999", priceNote: "per person, twin sharing", inclusions: ["Hampi guesthouse 2N", "Daily breakfast", "Virupaksha & Vittala temples", "Coracle boat ride", "AC cab from Bangalore"] },
      { name: "Hampi Explorer", duration: "3N/4D", price: "₹6,500", priceNote: "per person, twin sharing", inclusions: ["Hampi stay 3N", "Breakfast", "Full Hampi coverage", "Hospet & Tungabhadra dam", "Bicycle rental", "Sunset at Hemakuta Hill"], tag: "Most Popular" },
    ],
    faqs: [
      { q: "How far is Hampi from Bangalore?", a: "Hampi is ~350 km from Bangalore — 6 hours by road or overnight train to Hosapete (3 km from Hampi). We include cab or train booking in our packages." },
    ],
    related: ["goa-tour-from-bangalore", "coorg-ooty-tour-from-bangalore", "rajasthan-tour-from-bangalore"],
  },

  {
    slug: "honeymoon-packages-from-bangalore",
    title: "Honeymoon Packages from Bangalore",
    type: "domestic",
    heroImage: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=1600&q=85",
    heroAlt: "Best honeymoon packages from Bangalore — Maldives overwater bungalow",
    tagline: "Best romantic destinations — Kerala, Bali, Maldives & more from ₹18,000",
    startPrice: "₹18,000",
    popularDuration: "5N/6D",
    tripsCount: "800+",
    highlights: [
      { place: "Maldives", desc: "Overwater bungalows, crystal lagoons, private beaches — the world's #1 honeymoon destination." },
      { place: "Bali, Indonesia", desc: "Private pool villas, Ubud rice terraces, Seminyak sunset beach clubs." },
      { place: "Kerala Backwaters", desc: "Alleppey houseboat, Munnar misty hills, Kovalam beach — romantic & close by." },
      { place: "Kashmir", desc: "Dal Lake houseboats, Gulmarg meadows, Pahalgam valley — paradise on Earth." },
      { place: "Thailand", desc: "Phuket beach villas, Phi Phi island snorkelling, Bangkok rooftop dinners." },
      { place: "Coorg / Wayanad", desc: "Jungle resorts, private plunge pools, misty mornings — quick escape from Bangalore." },
    ],
    packages: [
      { name: "Kerala Honeymoon", duration: "5N/6D", price: "₹18,000", priceNote: "per couple", inclusions: ["Munnar 2N + Alleppey houseboat 1N + Kovalam 2N", "4-star resorts", "Candlelight dinner", "Couples spa", "Private cab", "Rose petal decoration"] },
      { name: "Bali Honeymoon", duration: "6N/7D", price: "₹38,000", priceNote: "per couple (without flight)", inclusions: ["Private pool villa 6N", "Breakfast & dinner", "Sunset Uluwatu temple", "Couples massage", "Nusa Penida island day trip", "Private driver"], tag: "Most Popular" },
      { name: "Maldives Honeymoon", duration: "4N/5D", price: "₹65,000", priceNote: "per couple (without flight)", inclusions: ["Overwater/beach villa 4N", "All meals (half board)", "Snorkelling & water activities", "Sunset dolphin cruise", "Private beach dinner"] },
    ],
    faqs: [
      { q: "Best honeymoon destinations from Bangalore?", a: "International: Maldives, Bali, Thailand, Mauritius, Singapore. Domestic: Kerala, Kashmir, Andaman, Coorg, Wayanad. We customise based on your budget and season." },
      { q: "What is the average cost of a honeymoon trip from Bangalore?", a: "Domestic honeymoons: ₹18,000–₹45,000 per couple (5–7 days). International honeymoons: ₹60,000–₹2,00,000 per couple depending on destination and hotel category." },
    ],
    related: ["bali-tour-from-bangalore", "maldives-tour-from-bangalore", "kerala-tour-from-bangalore"],
  },

  {
    slug: "group-tours-from-bangalore",
    title: "Group Tour Packages from Bangalore",
    type: "domestic",
    heroImage: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1600&q=85",
    heroAlt: "Group tours from Bangalore — corporate team outing",
    tagline: "Corporate outings, family group tours & pilgrimages — from ₹3,500/person",
    startPrice: "₹3,500",
    popularDuration: "2N/3D",
    tripsCount: "300+",
    highlights: [
      { place: "Corporate Team Outings", desc: "Coorg, Goa, Wayanad — activity-based team bonding with customised experiences." },
      { place: "Family Reunions", desc: "Multi-generational group trips with activities suited for all age groups." },
      { place: "Pilgrimage Tours", desc: "Varanasi, Char Dham, Tirupati, Shirdi — complete temple circuit packages." },
      { place: "College Group Tours", desc: "Budget-friendly packages for student groups with safety and fun in focus." },
      { place: "Ladies Group Tours", desc: "Women-only group trips with curated itineraries and experienced female guides." },
      { place: "Senior Citizen Tours", desc: "Comfortable paced trips with accessible transportation and medical support." },
    ],
    packages: [
      { name: "Weekend Group Outing", duration: "2N/3D", price: "₹3,500", priceNote: "per person (min 10 pax)", inclusions: ["Resort accommodation 2N", "All meals", "Group activities", "AC tempo traveller", "Event coordinator"] },
      { name: "Group Holiday Package", duration: "4N/5D", price: "₹7,500", priceNote: "per person (min 15 pax)", inclusions: ["3-star hotel 4N", "All meals", "Full sightseeing", "Group activities", "AC coach", "Dedicated trip manager"], tag: "Most Popular" },
      { name: "International Group Tour", duration: "6N/7D", price: "₹35,000", priceNote: "per person (min 20 pax), without flight", inclusions: ["Bali or Thailand", "4-star hotel", "All meals", "Group activities", "Guide", "Visa assistance", "Airport transfers"] },
    ],
    faqs: [
      { q: "What is the minimum group size for a group tour?", a: "We handle groups from 10 to 500+ people. Smaller groups get a per-person rate that decreases with larger numbers. Contact us for a group-specific quote." },
      { q: "Do you arrange corporate team outing packages from Bangalore?", a: "Yes — corporate outings are our specialty. We arrange venues, team activities, transportation, meals and customised itineraries for companies of any size." },
    ],
    related: ["goa-tour-from-bangalore", "coorg-ooty-tour-from-bangalore", "kerala-tour-from-bangalore"],
  },

  // ─── INTERNATIONAL ────────────────────────────────────────────────────────────

  {
    slug: "bali-tour-from-bangalore",
    title: "Bali Tour Packages from Bangalore",
    type: "international",
    heroImage: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1600&q=85",
    heroAlt: "Bali tour packages from Bangalore — Ubud rice terraces",
    tagline: "Ubud, Seminyak, Kuta & Nusa Penida — all-inclusive trips from ₹24,500",
    startPrice: "₹24,500",
    popularDuration: "5N/6D",
    tripsCount: "200+",
    visaNote: "Visa on Arrival (USD 35) for Indians",
    highlights: [
      { place: "Ubud", desc: "Tegallalang rice terraces, Sacred Monkey Forest, Tirta Empul temple & art markets." },
      { place: "Kuta & Legian", desc: "Famous beach strip with surfing, beach clubs and Bali's best sunsets." },
      { place: "Seminyak", desc: "Upscale villas, world-class restaurants and luxury beach clubs." },
      { place: "Nusa Penida", desc: "Kelingking Beach cliff views, Angel's Billabong, crystal snorkelling." },
      { place: "Tanah Lot", desc: "Iconic sea temple silhouetted against the sunset — Bali's most photographed landmark." },
      { place: "Uluwatu", desc: "Clifftop temple with Kecak fire dance and breathtaking ocean views." },
    ],
    packages: [
      { name: "Bali Budget", duration: "5N/6D", price: "₹24,500", priceNote: "per person, twin sharing (without flight)", inclusions: ["Kuta 2N + Ubud 2N + Seminyak 1N", "3-star villas", "Daily breakfast", "Kintamani volcano tour", "Tanah Lot", "Airport transfers"] },
      { name: "Bali Honeymoon", duration: "6N/7D", price: "₹38,500", priceNote: "per couple (without flight)", inclusions: ["Private pool villa 6N", "Ubud + Seminyak + Nusa Penida", "Candlelight dinner", "Couples spa", "Private driver", "Flower decoration"], tag: "Best for Couples" },
      { name: "Bali with Flight & Visa", duration: "5N/6D", price: "₹49,500", priceNote: "per person, incl. BLR–DPS flights", inclusions: ["Bangalore–Bali–Bangalore flights", "3-star hotel", "Breakfast", "Kuta, Ubud, Tanah Lot", "Visa on arrival guidance", "All transfers"], tag: "Most Convenient" },
    ],
    faqs: [
      { q: "Does Indian passport need visa for Bali?", a: "Indian passport holders get Bali Visa on Arrival (VoA) for stays up to 30 days at USD 35. We guide all customers through the Bali arrival process." },
      { q: "Best time to visit Bali from Bangalore?", a: "April–October (dry season) is ideal. July–August is peak — book early. November–March has occasional rain but lower prices." },
      { q: "Total cost of Bali trip for 2 from Bangalore?", a: "Budget 5N/6D for 2: ₹49,000–₹60,000 (without flights). With flights: ₹80,000–₹1,20,000 per couple depending on hotels and season." },
    ],
    related: ["singapore-tour-from-bangalore", "thailand-tour-from-bangalore", "honeymoon-packages-from-bangalore"],
  },

  {
    slug: "singapore-tour-from-bangalore",
    title: "Singapore Tour Packages from Bangalore",
    type: "international",
    heroImage: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=1600&q=85",
    heroAlt: "Singapore tour packages from Bangalore — Marina Bay Sands",
    tagline: "Marina Bay, Sentosa Island & Universal Studios — from ₹32,500",
    startPrice: "₹32,500",
    popularDuration: "5N/6D",
    tripsCount: "300+",
    visaNote: "Visa required (3–5 working days)",
    highlights: [
      { place: "Marina Bay Sands", desc: "Iconic infinity pool, Gardens by the Bay, light show at night." },
      { place: "Universal Studios Singapore", desc: "Asia's premier theme park — Transformers, Jurassic World, Minions rides." },
      { place: "Sentosa Island", desc: "Beaches, cable car, S.E.A. Aquarium and Adventure Cove Waterpark." },
      { place: "Gardens by the Bay", desc: "Supertree Grove, Flower Dome & Cloud Forest — futuristic botanical gardens." },
      { place: "Little India & Chinatown", desc: "Singapore's vibrant heritage neighbourhoods — street food, temples & markets." },
      { place: "Singapore Zoo & Night Safari", desc: "World-famous open-concept zoo and unique nocturnal Night Safari." },
    ],
    packages: [
      { name: "Singapore Standard", duration: "4N/5D", price: "₹32,500", priceNote: "per person, twin sharing (without flight)", inclusions: ["4-star hotel 4N", "Daily breakfast", "Universal Studios entry", "Gardens by the Bay", "Sentosa Island", "Visa assistance", "Transfers"] },
      { name: "Singapore + Malaysia", duration: "6N/7D", price: "₹42,000", priceNote: "per person, twin sharing (without flight)", inclusions: ["Singapore 4N + Kuala Lumpur 2N", "4-star hotels", "Breakfast", "Universal Studios", "Batu Caves KL", "Night safari", "All transfers"], tag: "Most Popular" },
      { name: "Singapore with Flight", duration: "5N/6D", price: "₹55,000", priceNote: "per person, incl. BLR–SIN flights", inclusions: ["Bangalore–Singapore–Bangalore flights", "4-star hotel", "Breakfast", "Universal Studios + Gardens", "Singapore visa", "All transfers"], tag: "Most Convenient" },
    ],
    faqs: [
      { q: "Do Indians need a visa for Singapore?", a: "Yes, Indian passport holders require a Singapore Tourist Visa (e-visa). Processing takes 3–5 working days. We handle all visa applications as part of our packages." },
      { q: "Best time to visit Singapore from Bangalore?", a: "Singapore is a year-round destination with warm weather (26–33°C). February–April is drier. November–January has more rain but Great Singapore Sale is in June–July." },
      { q: "Is Singapore good for families from Bangalore?", a: "Excellent — Universal Studios, S.E.A. Aquarium, Singapore Zoo, Night Safari and Sentosa Island are all world-class family experiences." },
    ],
    related: ["bali-tour-from-bangalore", "malaysia-tour-from-bangalore", "thailand-tour-from-bangalore"],
  },

  {
    slug: "thailand-tour-from-bangalore",
    title: "Thailand Tour Packages from Bangalore",
    type: "international",
    heroImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1600&q=85",
    heroAlt: "Thailand Bangkok Phuket tour from Bangalore",
    tagline: "Bangkok, Phuket, Pattaya & Krabi — from ₹28,000",
    startPrice: "₹28,000",
    popularDuration: "5N/6D",
    tripsCount: "350+",
    visaNote: "Visa on Arrival for Indians (free as of 2024)",
    highlights: [
      { place: "Bangkok", desc: "Grand Palace, Wat Pho reclining Buddha, Floating Market, Chatuchak weekend market." },
      { place: "Phuket", desc: "Patong Beach, Phi Phi island day trip, Big Buddha & Old Phuket Town." },
      { place: "Pattaya", desc: "Coral Island, underwater world, walking street & Nong Nooch Tropical Garden." },
      { place: "Krabi", desc: "Railay Beach, Tiger Cave Temple, island hopping by longtail boat." },
      { place: "Chiang Mai", desc: "Elephant sanctuary, night bazaar, Doi Suthep temple & cooking classes." },
      { place: "Phi Phi Islands", desc: "Maya Bay (The Beach), snorkelling, diving & dramatic limestone cliffs." },
    ],
    packages: [
      { name: "Bangkok-Pattaya", duration: "5N/6D", price: "₹28,000", priceNote: "per person, twin sharing (without flight)", inclusions: ["Bangkok 3N + Pattaya 2N", "4-star hotel", "Daily breakfast", "Floating Market, Coral Island", "All transfers", "Visa assistance"] },
      { name: "Bangkok-Phuket", duration: "6N/7D", price: "₹35,000", priceNote: "per person, twin sharing (without flight)", inclusions: ["Bangkok 3N + Phuket 3N", "4-star hotels", "Breakfast & dinner", "Phi Phi island tour", "James Bond island", "Elephant show", "All transfers"], tag: "Most Popular" },
      { name: "Thailand with Flight", duration: "5N/6D", price: "₹48,000", priceNote: "per person, incl. BLR–BKK flights", inclusions: ["Bangalore–Bangkok–Bangalore flights", "Bangkok + Pattaya", "4-star hotel", "Breakfast", "All sightseeing", "Transfers"], tag: "Most Convenient" },
    ],
    faqs: [
      { q: "Do Indians need a visa for Thailand?", a: "India has visa-free/visa-on-arrival access to Thailand. As of 2024, Indian citizens can enter visa-free for 30 days. Confirm current rules before travel — we update customers on latest requirements." },
      { q: "Best time to visit Thailand from Bangalore?", a: "November–February is perfect — cool and dry. March–May is hot. June–October is monsoon (Southern Thailand stays dry while North is wet, and vice versa)." },
    ],
    related: ["bali-tour-from-bangalore", "singapore-tour-from-bangalore", "vietnam-malaysia-tour-from-bangalore"],
  },

  {
    slug: "dubai-tour-from-bangalore",
    title: "Dubai Tour Packages from Bangalore",
    type: "international",
    heroImage: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1600&q=85",
    heroAlt: "Dubai tour packages from Bangalore — Burj Khalifa skyline",
    tagline: "Burj Khalifa, Desert Safari & Dubai Frame — from ₹31,500",
    startPrice: "₹31,500",
    popularDuration: "5N/6D",
    tripsCount: "400+",
    visaNote: "UAE Visa required (2–3 working days)",
    highlights: [
      { place: "Burj Khalifa", desc: "World's tallest building — observation deck at 124th or 148th floor." },
      { place: "Desert Safari", desc: "Dune bashing, camel ride, sandboarding, belly dance & BBQ dinner under stars." },
      { place: "Dubai Mall & Fountain Show", desc: "World's largest mall + Dubai Fountain — largest choreographed fountain on Earth." },
      { place: "Palm Jumeirah", desc: "The iconic man-made palm island — Atlantis, monorail & beach clubs." },
      { place: "Old Dubai (Deira)", desc: "Gold Souk, Spice Souk, abra ride on Dubai Creek — authentic old Arabia." },
      { place: "Abu Dhabi Day Trip", desc: "Sheikh Zayed Grand Mosque, Louvre Abu Dhabi, Ferrari World." },
    ],
    packages: [
      { name: "Dubai Standard", duration: "4N/5D", price: "₹31,500", priceNote: "per person, twin sharing (without flight)", inclusions: ["Dubai 4-star hotel 4N", "Daily breakfast", "Burj Khalifa 124th floor", "Desert Safari", "Dubai Mall + Fountain", "UAE visa", "All transfers"] },
      { name: "Dubai + Abu Dhabi", duration: "5N/6D", price: "₹39,500", priceNote: "per person, twin sharing (without flight)", inclusions: ["Dubai 4N + Abu Dhabi day trip", "4-star hotel", "Breakfast & dinner", "Sheikh Zayed Mosque", "Ferrari World", "Desert Safari", "Palm Jumeirah", "UAE visa"], tag: "Most Popular" },
      { name: "Dubai with Flight", duration: "4N/5D", price: "₹52,000", priceNote: "per person, incl. BLR–DXB flights", inclusions: ["Bangalore–Dubai–Bangalore flights", "4-star hotel", "Breakfast", "Burj Khalifa", "Desert Safari", "UAE visa", "All transfers"], tag: "Most Convenient" },
    ],
    faqs: [
      { q: "Do Indians need a visa for Dubai?", a: "Yes — Indian passport holders need a UAE Tourist Visa. Processing takes 2–3 working days. We handle UAE visa applications as part of all Dubai packages." },
      { q: "Best time to visit Dubai from Bangalore?", a: "October–April is ideal — cool and pleasant (22–32°C). May–September is extremely hot (40–45°C) but hotels are cheaper. Dubai has indoor attractions year-round." },
    ],
    related: ["singapore-tour-from-bangalore", "maldives-tour-from-bangalore", "bali-tour-from-bangalore"],
  },

  {
    slug: "maldives-tour-from-bangalore",
    title: "Maldives Tour Packages from Bangalore",
    type: "international",
    heroImage: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=1600&q=85",
    heroAlt: "Maldives overwater villa tour from Bangalore — honeymoon package",
    tagline: "Overwater villas, coral reefs & private beaches — from ₹43,000",
    startPrice: "₹43,000",
    popularDuration: "4N/5D",
    tripsCount: "150+",
    visaNote: "Free visa on arrival for Indians (30 days)",
    highlights: [
      { place: "Overwater Bungalows", desc: "Stilted villas above the turquoise lagoon — wake up to the ocean below." },
      { place: "Snorkelling & Diving", desc: "World-class coral reefs, manta rays, whale sharks & turtles." },
      { place: "Sandbank Picnic", desc: "Private sandbank surrounded by 360° ocean — romantic & exclusive." },
      { place: "Bioluminescent Beach", desc: "Glowing plankton lighting up the shoreline at night — magical experience." },
      { place: "Sunset Dolphin Cruise", desc: "Catamaran cruise with dolphin sightings — one of Maldives' most popular activities." },
      { place: "Underwater Restaurant", desc: "Dine beneath the ocean — unique fine dining experience." },
    ],
    packages: [
      { name: "Maldives Budget", duration: "3N/4D", price: "₹43,000", priceNote: "per couple (without flight)", inclusions: ["Beach villa/water bungalow 3N", "Half board (breakfast & dinner)", "Snorkelling trip", "Sunset cruise", "Airport speedboat transfers"] },
      { name: "Maldives Honeymoon", duration: "4N/5D", price: "₹65,000", priceNote: "per couple (without flight)", inclusions: ["Overwater villa 4N", "All meals + sunset cruise", "Couple spa", "Private sandbank picnic", "Snorkelling & diving session", "Romantic beach dinner"], tag: "Best for Couples" },
      { name: "Maldives with Flight", duration: "4N/5D", price: "₹85,000", priceNote: "per couple, incl. BLR–MLE flights", inclusions: ["Bangalore–Malé–Bangalore flights", "Beach/water villa 4N", "Half board", "Snorkelling", "Sunset cruise", "Speedboat transfers"], tag: "All Inclusive" },
    ],
    faqs: [
      { q: "Do Indians need a visa for Maldives?", a: "No — Indian passport holders get a free visa on arrival for 30 days. Just show hotel booking and return ticket at immigration." },
      { q: "Best time to visit Maldives from Bangalore?", a: "November–April (dry season) is ideal. January–March is peak with best visibility for diving. May–October is wet season — rough seas but budget prices." },
    ],
    related: ["bali-tour-from-bangalore", "thailand-tour-from-bangalore", "honeymoon-packages-from-bangalore"],
  },

  {
    slug: "europe-tour-from-bangalore",
    title: "Europe Tour Packages from Bangalore",
    type: "international",
    heroImage: "https://images.unsplash.com/photo-1491557345352-5929e343eb89?w=1600&q=85",
    heroAlt: "Europe tour packages from Bangalore — Paris Eiffel Tower",
    tagline: "Paris, Switzerland, Italy & more — Western Europe from ₹80,000",
    startPrice: "₹80,000",
    popularDuration: "8N/9D",
    tripsCount: "200+",
    visaNote: "Schengen Visa required (10–15 working days)",
    highlights: [
      { place: "Paris, France", desc: "Eiffel Tower, Louvre Museum, Seine river cruise & Versailles Palace." },
      { place: "Switzerland", desc: "Jungfraujoch (Top of Europe), Interlaken paragliding, Lucerne & Zurich." },
      { place: "Rome, Italy", desc: "Colosseum, Vatican City, Trevi Fountain & Roman Forum." },
      { place: "Barcelona, Spain", desc: "Sagrada Familia, Park Güell, Las Ramblas & tapas culture." },
      { place: "Amsterdam, Netherlands", desc: "Anne Frank House, canal boat rides, tulip fields & cycling." },
      { place: "Prague, Czech Republic", desc: "Old Town Square, Charles Bridge, Prague Castle — fairytale city." },
    ],
    packages: [
      { name: "Western Europe Classic", duration: "8N/9D", price: "₹80,000", priceNote: "per person (without flight)", inclusions: ["Paris 3N + Switzerland 2N + Italy 3N", "3-star hotels", "Daily breakfast", "Coach transfers between cities", "Schengen visa assistance", "City tours"] },
      { name: "Europe Grand Tour", duration: "12N/13D", price: "₹1,10,000", priceNote: "per person (without flight)", inclusions: ["5 countries: France, Switzerland, Italy, Austria, Germany", "4-star hotels", "Breakfast & dinner", "Rail passes", "All city tours", "Visa assistance"], tag: "Most Popular" },
      { name: "Europe with Flights", duration: "9N/10D", price: "₹1,45,000", priceNote: "per person, incl. BLR–CDG flights", inclusions: ["Bangalore–Paris–Bangalore flights", "Paris + Switzerland + Rome", "4-star hotels", "Breakfast", "All tours", "Schengen visa"], tag: "Best Value" },
    ],
    faqs: [
      { q: "How long does it take to get a Schengen visa from Bangalore?", a: "Schengen visa processing takes 10–15 working days from Bangalore. Apply at least 4–6 weeks before travel. We handle all documentation and submission." },
      { q: "Best time to visit Europe from Bangalore?", a: "April–June and September–October are ideal — pleasant weather, manageable crowds. July–August is peak summer — crowded and expensive. December–February is cold but Christmas markets are magical." },
    ],
    related: ["dubai-tour-from-bangalore", "singapore-tour-from-bangalore", "services/visa-agent-bangalore"],
  },

  {
    slug: "sri-lanka-tour-from-bangalore",
    title: "Sri Lanka Tour Packages from Bangalore",
    type: "international",
    heroImage: "https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?w=1600&q=85",
    heroAlt: "Sri Lanka Colombo Sigiriya tour from Bangalore",
    tagline: "Colombo, Sigiriya, Kandy & beaches — from ₹22,500",
    startPrice: "₹22,500",
    popularDuration: "5N/6D",
    tripsCount: "200+",
    visaNote: "ETA Online (USD 35, instant approval)",
    highlights: [
      { place: "Sigiriya Rock Fortress", desc: "UNESCO Heritage — lion rock with ancient frescoes and water gardens at 200 m." },
      { place: "Kandy — Temple of the Tooth", desc: "Sacred Buddhist temple with the tooth relic of Lord Buddha." },
      { place: "Nuwara Eliya", desc: "Ceylon tea estate tours, Victoria Park & hill station atmosphere." },
      { place: "Mirissa Beach", desc: "Whale watching, surfing and relaxed beach vibes in south Sri Lanka." },
      { place: "Galle Fort", desc: "17th-century Dutch fort — cobblestone streets, lighthouse & ocean views." },
      { place: "Colombo", desc: "Gangaramaya Temple, Pettah Market, Galle Face Green promenade." },
    ],
    packages: [
      { name: "Sri Lanka Highlights", duration: "5N/6D", price: "₹22,500", priceNote: "per person, twin sharing (without flight)", inclusions: ["Colombo 1N + Sigiriya 1N + Kandy 2N + Bentota 1N", "3-star hotels", "Daily breakfast", "All sightseeing", "Transfers", "ETA visa assistance"] },
      { name: "Sri Lanka + Beaches", duration: "7N/8D", price: "₹32,000", priceNote: "per person, twin sharing (without flight)", inclusions: ["Colombo + Sigiriya + Kandy + Nuwara Eliya + Mirissa", "3-star hotels + beach resort", "Breakfast & dinner", "Whale watching", "All transfers"], tag: "Most Popular" },
      { name: "Sri Lanka with Flight", duration: "5N/6D", price: "₹38,000", priceNote: "per person, incl. BLR–CMB flights", inclusions: ["Bangalore–Colombo–Bangalore flights", "Tour as above", "ETA visa", "All transfers"] },
    ],
    faqs: [
      { q: "Do Indians need a visa for Sri Lanka?", a: "Yes — an Electronic Travel Authorisation (ETA) is required, costs USD 35 and is usually approved within a few hours online. We assist all our customers with the ETA application." },
      { q: "Best time to visit Sri Lanka from Bangalore?", a: "Sri Lanka has two monsoon seasons. West & south coast: November–April (dry). East coast: May–September. Year-round destination with some part always being sunny." },
    ],
    related: ["maldives-tour-from-bangalore", "bali-tour-from-bangalore", "thailand-tour-from-bangalore"],
  },

  {
    slug: "vietnam-malaysia-tour-from-bangalore",
    title: "Vietnam & Malaysia Tour Packages from Bangalore",
    type: "international",
    heroImage: "https://images.unsplash.com/photo-1557750255-c76072a7aad1?w=1600&q=85",
    heroAlt: "Vietnam Halong Bay Malaysia Kuala Lumpur tour from Bangalore",
    tagline: "Hanoi, Halong Bay, Ho Chi Minh City & Kuala Lumpur — from ₹35,000",
    startPrice: "₹35,000",
    popularDuration: "7N/8D",
    tripsCount: "150+",
    visaNote: "Vietnam e-Visa (USD 25) + Malaysia visa-free for Indians",
    highlights: [
      { place: "Hanoi Old Quarter", desc: "French colonial architecture, Hoan Kiem Lake, Ngoc Son Temple & street food." },
      { place: "Halong Bay", desc: "UNESCO Heritage — 1,969 limestone islands, overnight cruise & kayaking." },
      { place: "Ho Chi Minh City", desc: "Cu Chi Tunnels, War Remnants Museum, Ben Thanh Market & rooftop bars." },
      { place: "Kuala Lumpur", desc: "Petronas Twin Towers, Batu Caves, KL Tower & Little India." },
      { place: "Hoi An Ancient Town", desc: "UNESCO Heritage — lantern-lit streets, tailor shops, beach town." },
      { place: "Penang, Malaysia", desc: "Street food capital of Asia, George Town heritage, tribal hill tribes." },
    ],
    packages: [
      { name: "Vietnam Highlights", duration: "6N/7D", price: "₹35,000", priceNote: "per person, twin sharing (without flight)", inclusions: ["Hanoi 2N + Halong Bay cruise 1N + Hoi An 2N + HCMC 1N", "3-star hotels", "Breakfast", "Halong Bay overnight cruise", "Cu Chi Tunnels", "e-Visa", "Transfers"] },
      { name: "Vietnam + Malaysia", duration: "9N/10D", price: "₹52,000", priceNote: "per person, twin sharing (without flight)", inclusions: ["Vietnam 6N + Kuala Lumpur 3N", "4-star hotels", "Breakfast", "Halong Bay cruise", "Petronas Towers", "Batu Caves", "Vietnam visa", "Transfers"], tag: "Most Popular" },
      { name: "With Flights", duration: "7N/8D", price: "₹60,000", priceNote: "per person, incl. BLR–HAN / KUL–BLR flights", inclusions: ["Bangalore–Hanoi + KL–Bangalore flights", "Vietnam + KL highlights", "4-star hotels", "Breakfast", "Visa assistance", "Transfers"] },
    ],
    faqs: [
      { q: "Do Indians need a visa for Vietnam?", a: "Yes — an e-Visa is required (USD 25, valid 90 days). Processing takes 3 working days. Malaysia is visa-free for Indians for up to 30 days." },
      { q: "Best time to visit Vietnam from Bangalore?", a: "November–April for North Vietnam and beaches. Central Vietnam (Hoi An) is best October–January. South Vietnam is year-round. Avoid typhoon season (August–October) in Central Vietnam." },
    ],
    related: ["bali-tour-from-bangalore", "thailand-tour-from-bangalore", "singapore-tour-from-bangalore"],
  },

  {
    slug: "malaysia-tour-from-bangalore",
    title: "Malaysia Tour Packages from Bangalore",
    type: "international",
    heroImage: "https://images.unsplash.com/photo-1596422846543-75c6fc197f11?w=1600&q=85",
    heroAlt: "Malaysia Kuala Lumpur Petronas Twin Towers tour from Bangalore",
    tagline: "Kuala Lumpur, Penang, Langkawi & Genting — from ₹28,000",
    startPrice: "₹28,000",
    popularDuration: "5N/6D",
    tripsCount: "200+",
    visaNote: "Visa-free for Indians (30 days)",
    highlights: [
      { place: "Kuala Lumpur", desc: "Petronas Twin Towers, KL Tower, Batu Caves Hindu temple, Bukit Bintang." },
      { place: "Langkawi", desc: "Duty-free island — cable car, mangrove kayaking, clear beaches." },
      { place: "Penang", desc: "George Town UNESCO Heritage, Clan Jetties, best street food in Asia." },
      { place: "Genting Highlands", desc: "Theme park resort in the clouds — casinos, indoor skiing, cable car." },
      { place: "Cameron Highlands", desc: "Tea plantations, strawberry farms, butterfly park & cool climate." },
      { place: "Malacca", desc: "UNESCO Heritage city — Dutch Square, Christ Church, Jonker Street." },
    ],
    packages: [
      { name: "Kuala Lumpur-Genting", duration: "4N/5D", price: "₹28,000", priceNote: "per person, twin sharing (without flight)", inclusions: ["KL 3N + Genting 1N", "4-star hotel", "Daily breakfast", "Petronas Towers", "Batu Caves", "Genting cable car", "All transfers"] },
      { name: "Malaysia Highlights", duration: "6N/7D", price: "₹38,000", priceNote: "per person, twin sharing (without flight)", inclusions: ["KL 3N + Penang 2N + Langkawi 1N", "4-star hotels", "Breakfast & dinner", "All sightseeing", "Cable cars", "Domestic transfers"], tag: "Most Popular" },
      { name: "Malaysia with Flight", duration: "5N/6D", price: "₹48,000", priceNote: "per person, incl. BLR–KUL flights", inclusions: ["Bangalore–KL–Bangalore flights", "KL + Genting", "4-star hotel", "Breakfast", "All tours", "Transfers"] },
    ],
    faqs: [
      { q: "Do Indians need a visa for Malaysia?", a: "No — Indian passport holders get visa-free entry to Malaysia for up to 30 days. Just show hotel booking and return ticket." },
    ],
    related: ["singapore-tour-from-bangalore", "thailand-tour-from-bangalore", "vietnam-malaysia-tour-from-bangalore"],
  },

  {
    slug: "mauritius-tour-from-bangalore",
    title: "Mauritius Tour Packages from Bangalore",
    type: "international",
    heroImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&q=85",
    heroAlt: "Mauritius beach resort tour from Bangalore — honeymoon package",
    tagline: "Turquoise lagoons, luxury resorts & Chamarel Seven Coloured Earth — from ₹55,000",
    startPrice: "₹55,000",
    popularDuration: "5N/6D",
    tripsCount: "100+",
    visaNote: "Visa-free for Indians (60 days)",
    highlights: [
      { place: "Grand Baie", desc: "Beach resort strip, water sports, boat trips to Northern islands." },
      { place: "Chamarel Seven Coloured Earth", desc: "Unique multi-coloured sand dunes — natural phenomenon + Chamarel waterfalls." },
      { place: "Black River Gorges National Park", desc: "Jungle trekking, endemic birds & Tamarin Falls." },
      { place: "Île aux Cerfs", desc: "Lush private island lagoon — snorkelling, water sports & beach BBQ." },
      { place: "Underwater Waterfall", desc: "Optical illusion waterfall viewed by helicopter — Mauritius' most iconic image." },
      { place: "Port Louis", desc: "Colourful Central Market, Blue Penny Museum, Caudan Waterfront." },
    ],
    packages: [
      { name: "Mauritius Standard", duration: "5N/6D", price: "₹55,000", priceNote: "per couple (without flight)", inclusions: ["4-star beach resort 5N", "Daily breakfast", "Île aux Cerfs day trip", "Chamarel tour", "Water sports", "Airport transfers"] },
      { name: "Mauritius Honeymoon", duration: "6N/7D", price: "₹75,000", priceNote: "per couple (without flight)", inclusions: ["5-star resort 6N", "All meals + sunset cruise", "Couples spa", "Private beach dinner", "Helicopter tour", "Island tour"], tag: "Best for Couples" },
    ],
    faqs: [
      { q: "Do Indians need a visa for Mauritius?", a: "No — Indian passport holders get visa-free entry for 60 days. One of the easiest destinations for Indians to visit." },
    ],
    related: ["maldives-tour-from-bangalore", "bali-tour-from-bangalore", "honeymoon-packages-from-bangalore"],
  },

  {
    slug: "nepal-tour-from-bangalore",
    title: "Nepal Tour Packages from Bangalore",
    type: "international",
    heroImage: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1600&q=85",
    heroAlt: "Nepal Kathmandu Pokhara tour from Bangalore — Himalayan mountains",
    tagline: "Kathmandu, Pokhara, Everest Base Camp & Chitwan — from ₹14,500",
    startPrice: "₹14,500",
    popularDuration: "5N/6D",
    tripsCount: "200+",
    visaNote: "Visa on arrival for Indians (free)",
    highlights: [
      { place: "Kathmandu Valley", desc: "Pashupatinath Temple, Boudhanath Stupa, Swayambhunath & Durbar Square." },
      { place: "Pokhara", desc: "Phewa Lake boating, Annapurna views, Peace Pagoda, Davis Falls." },
      { place: "Nagarkot Sunrise", desc: "Sunrise over the Himalayan range including Everest — most popular sunrise view in Nepal." },
      { place: "Chitwan National Park", desc: "Jungle safari for one-horned rhino, Bengal tiger and gharial crocodile." },
      { place: "Everest Base Camp Trek", desc: "16-day trek to 5,364 m — one of the world's great trekking adventures." },
      { place: "Lumbini", desc: "Birthplace of Lord Buddha — Maya Devi Temple & UNESCO Heritage site." },
    ],
    packages: [
      { name: "Kathmandu-Pokhara", duration: "5N/6D", price: "₹14,500", priceNote: "per person, twin sharing (without flight)", inclusions: ["Kathmandu 3N + Pokhara 2N", "3-star hotel", "Daily breakfast", "Pashupatinath, Boudhanath", "Phewa Lake", "Airport transfers"] },
      { name: "Nepal Highlights", duration: "7N/8D", price: "₹19,500", priceNote: "per person, twin sharing (without flight)", inclusions: ["Kathmandu 3N + Nagarkot 1N + Pokhara 2N + Chitwan 1N", "3-star hotels", "Breakfast & dinner", "Chitwan safari", "Sunrise view", "All transfers"], tag: "Most Popular" },
      { name: "Nepal with Flight", duration: "6N/7D", price: "₹28,000", priceNote: "per person, incl. BLR–KTM flights", inclusions: ["Bangalore–Kathmandu–Bangalore flights", "Complete Kathmandu + Pokhara", "Hotels", "Breakfast", "All sightseeing", "Transfers"] },
    ],
    faqs: [
      { q: "Do Indians need a visa for Nepal?", a: "No — Indian passport holders can enter Nepal visa-free with any valid Indian photo ID (Aadhaar or passport). No visa required." },
      { q: "Best time to visit Nepal from Bangalore?", a: "March–May (spring) and October–November (autumn) are ideal — clear mountain views. December–February is cold but clear. June–September monsoon is wet but good for Chitwan." },
    ],
    related: ["uttarakhand-tour-from-bangalore", "bhutan-tour-from-bangalore", "kashmir-tour-from-bangalore"],
  },

  {
    slug: "bhutan-tour-from-bangalore",
    title: "Bhutan Tour Packages from Bangalore",
    type: "international",
    heroImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1600&q=85",
    heroAlt: "Bhutan Paro Taktsang Tiger Nest tour from Bangalore",
    tagline: "Paro Tiger's Nest, Thimphu & Punakha Dzong — from ₹22,000",
    startPrice: "₹22,000",
    popularDuration: "5N/6D",
    tripsCount: "100+",
    visaNote: "Indian nationals can enter with any valid photo ID (no separate visa)",
    highlights: [
      { place: "Paro Taktsang (Tiger's Nest)", desc: "Iconic monastery clinging to a 3,000 m cliff — Bhutan's most photographed sight." },
      { place: "Thimphu", desc: "Bhutan's capital — Buddha Dordenma statue, Tashichho Dzong, local market." },
      { place: "Punakha Dzong", desc: "17th-century fortress at the confluence of two rivers — stunning architecture." },
      { place: "Haa Valley", desc: "Remote, pristine valley — traditional Bhutanese villages & festivals." },
      { place: "Dochula Pass", desc: "108 memorial chortens at 3,100 m with Himalayan views on clear days." },
      { place: "Phobjikha Valley", desc: "Wide glacial valley — winter home of Black-necked Cranes." },
    ],
    packages: [
      { name: "Bhutan Classic", duration: "5N/6D", price: "₹22,000", priceNote: "per person, twin sharing (without flight)", inclusions: ["Paro 2N + Thimphu 2N + Punakha 1N", "3-star hotel", "Daily breakfast & dinner", "Tiger's Nest hike", "Punakha Dzong", "All transfers"] },
      { name: "Bhutan Explorer", duration: "7N/8D", price: "₹32,000", priceNote: "per person, twin sharing (without flight)", inclusions: ["Paro + Thimphu + Punakha + Haa Valley", "4-star hotel", "All meals", "All dzongs & monasteries", "Local guide", "All transfers"], tag: "Most Popular" },
    ],
    faqs: [
      { q: "Do Indians need a visa for Bhutan?", a: "No separate visa — Indian nationals can enter Bhutan with a valid passport or government photo ID. However, Indian tourists are now required to pay a Sustainable Development Fee." },
    ],
    related: ["nepal-tour-from-bangalore", "kashmir-tour-from-bangalore", "uttarakhand-tour-from-bangalore"],
  },

  {
    slug: "turkey-tour-from-bangalore",
    title: "Turkey Tour Packages from Bangalore",
    type: "international",
    heroImage: "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?w=1600&q=85",
    heroAlt: "Turkey Istanbul Cappadocia hot air balloon tour from Bangalore",
    tagline: "Istanbul, Cappadocia, Pamukkale & Turkish Riviera — from ₹65,000",
    startPrice: "₹65,000",
    popularDuration: "7N/8D",
    tripsCount: "80+",
    visaNote: "e-Visa required (2–3 working days, USD 60 approx)",
    highlights: [
      { place: "Istanbul", desc: "Hagia Sophia, Blue Mosque, Topkapi Palace, Grand Bazaar & Bosphorus cruise." },
      { place: "Cappadocia", desc: "Hot air balloon over fairy chimneys — one of the world's most iconic experiences." },
      { place: "Pamukkale", desc: "Cotton Castle — white terraced hot spring pools & ancient Hierapolis ruins." },
      { place: "Ephesus", desc: "Best-preserved ancient Roman city — Library of Celsus, Amphitheatre." },
      { place: "Antalya (Turkish Riviera)", desc: "Mediterranean beaches, old town Kaleiçi & Düden Waterfalls." },
      { place: "Konya", desc: "Rumi's Mausoleum, whirling dervish ceremony — spiritual heart of Anatolia." },
    ],
    packages: [
      { name: "Turkey Classic", duration: "7N/8D", price: "₹65,000", priceNote: "per person (without flight)", inclusions: ["Istanbul 3N + Cappadocia 2N + Pamukkale 1N + Ephesus 1N", "4-star hotels", "Daily breakfast", "Hot air balloon", "All city tours", "e-Visa assistance", "Transfers"] },
      { name: "Turkey with Flight", duration: "8N/9D", price: "₹95,000", priceNote: "per person, incl. BLR–IST flights", inclusions: ["Bangalore–Istanbul–Bangalore flights", "Full Turkey tour", "4-star hotels", "Breakfast", "Hot air balloon", "e-Visa", "Transfers"], tag: "Most Popular" },
    ],
    faqs: [
      { q: "Do Indians need a visa for Turkey?", a: "Yes — an e-Visa is required for Indian passport holders, costing approximately USD 60. Processing takes 2–3 working days. We assist with all e-Visa applications." },
      { q: "Best time to visit Turkey from Bangalore?", a: "April–June and September–October are ideal — mild weather, fewer crowds than summer. July–August is hot and crowded. December–February is cold in Istanbul and Cappadocia but cheapest." },
    ],
    related: ["europe-tour-from-bangalore", "dubai-tour-from-bangalore", "services/visa-agent-bangalore"],
  },

  {
    slug: "japan-tour-from-bangalore",
    title: "Japan Tour Packages from Bangalore",
    type: "international",
    heroImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1600&q=85",
    heroAlt: "Japan Tokyo Kyoto Mount Fuji tour from Bangalore",
    tagline: "Tokyo, Kyoto, Osaka & Mount Fuji — from ₹85,000",
    startPrice: "₹85,000",
    popularDuration: "8N/9D",
    tripsCount: "60+",
    visaNote: "Japan Visa required (5–7 working days)",
    highlights: [
      { place: "Tokyo", desc: "Shibuya crossing, Senso-ji, teamLab Borderless, Akihabara & Harajuku." },
      { place: "Kyoto", desc: "Arashiyama Bamboo Grove, Fushimi Inari thousands of torii gates, Geisha district." },
      { place: "Osaka", desc: "Dotonbori street food, Osaka Castle, Universal Studios Japan." },
      { place: "Mount Fuji", desc: "Japan's most iconic peak — Fuji Five Lakes, Hakone, bullet train views." },
      { place: "Hiroshima & Miyajima", desc: "Peace Memorial Park, floating torii gate — powerful and poignant." },
      { place: "Nara", desc: "Free-roaming deer, Todai-ji with giant bronze Buddha." },
    ],
    packages: [
      { name: "Japan Classic", duration: "8N/9D", price: "₹85,000", priceNote: "per person (without flight)", inclusions: ["Tokyo 3N + Kyoto 3N + Osaka 2N + Hakone 1N", "3-star hotels", "Daily breakfast", "JR Rail Pass (7 days)", "City tours", "Visa assistance", "Transfers"] },
      { name: "Japan with Flights", duration: "9N/10D", price: "₹1,25,000", priceNote: "per person, incl. BLR–TYO flights", inclusions: ["Bangalore–Tokyo–Bangalore flights", "Full itinerary above", "4-star hotels", "Breakfast", "JR Pass", "Visa", "Transfers"], tag: "Most Popular" },
    ],
    faqs: [
      { q: "Do Indians need a visa for Japan?", a: "Yes — Japan Tourist Visa required for Indian nationals. Processing at Japan Consulate Bengaluru takes 5–7 working days. We handle all documentation." },
      { q: "Best time to visit Japan from Bangalore?", a: "March–April (cherry blossom — sakura season) is magical and the most popular time. November (autumn foliage) is equally beautiful. Avoid July–August (hot & humid) and typhoon season (September)." },
    ],
    related: ["singapore-tour-from-bangalore", "bali-tour-from-bangalore", "south-korea-tour-from-bangalore"],
  },

  {
    slug: "australia-tour-from-bangalore",
    title: "Australia Tour Packages from Bangalore",
    type: "international",
    heroImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1600&q=85",
    heroAlt: "Australia Sydney Opera House tour from Bangalore",
    tagline: "Sydney, Melbourne, Gold Coast & Great Barrier Reef — from ₹95,000",
    startPrice: "₹95,000",
    popularDuration: "10N/11D",
    tripsCount: "80+",
    visaNote: "ETA or eVisitor visa required (3–5 working days)",
    highlights: [
      { place: "Sydney", desc: "Opera House, Harbour Bridge climb, Bondi Beach & Darling Harbour." },
      { place: "Melbourne", desc: "Great Ocean Road, 12 Apostles, Queen Victoria Market, laneways & café culture." },
      { place: "Gold Coast", desc: "Theme parks (Movie World, Sea World), Surfers Paradise beach & hinterland." },
      { place: "Great Barrier Reef", desc: "World's largest coral reef — snorkelling, diving & glass-bottom boat rides." },
      { place: "Uluru (Ayers Rock)", desc: "Sacred red monolith in the Outback — spectacular sunrise and sunset views." },
      { place: "Cairns", desc: "Rainforest skywalk, Kuranda scenic railway & reef diving base." },
    ],
    packages: [
      { name: "Australia East Coast", duration: "10N/11D", price: "₹95,000", priceNote: "per person (without flight)", inclusions: ["Sydney 4N + Melbourne 3N + Gold Coast 3N", "4-star hotels", "Daily breakfast", "City tours", "Great Ocean Road", "Theme park entry", "Visa assistance", "Transfers"] },
      { name: "Australia with Flights", duration: "10N/11D", price: "₹1,45,000", priceNote: "per person, incl. BLR–SYD flights", inclusions: ["Bangalore–Sydney–Bangalore flights", "Full East Coast tour", "4-star hotels", "Breakfast", "Visa", "Transfers"], tag: "Most Popular" },
    ],
    faqs: [
      { q: "Do Indians need a visa for Australia?", a: "Yes — an ETA (Electronic Travel Authority) or eVisitor visa is required. Processing takes 1–5 working days. We handle all Australian visa applications." },
    ],
    related: ["new-zealand-tour-from-bangalore", "singapore-tour-from-bangalore", "services/visa-agent-bangalore"],
  },

  {
    slug: "new-zealand-tour-from-bangalore",
    title: "New Zealand Tour Packages from Bangalore",
    type: "international",
    heroImage: "https://images.unsplash.com/photo-1469521669194-babb45599def?w=1600&q=85",
    heroAlt: "New Zealand South Island Milford Sound tour from Bangalore",
    tagline: "Milford Sound, Queenstown & Hobbiton — Adventure Capital from ₹1,05,000",
    startPrice: "₹1,05,000",
    popularDuration: "10N/11D",
    tripsCount: "40+",
    visaNote: "Visitor Visa required (10–15 working days)",
    highlights: [
      { place: "Queenstown", desc: "World's adventure capital — bungee jumping, skydiving, jet boating, skiing." },
      { place: "Milford Sound", desc: "Fiordland fjord — cruise through dramatic cliffs, waterfalls & dolphins." },
      { place: "Hobbiton (Matamata)", desc: "The real Shire from Lord of the Rings — movie set tours in the Waikato." },
      { place: "Rotorua", desc: "Geothermal geysers, Maori cultural show, mud pools & Rainbow Springs." },
      { place: "Auckland", desc: "Sky Tower, Waiheke Island wineries, Waitomo glowworm caves." },
      { place: "Fox & Franz Josef Glaciers", desc: "Walk on ancient glaciers or take a helicopter flight over them." },
    ],
    packages: [
      { name: "New Zealand North + South", duration: "10N/11D", price: "₹1,05,000", priceNote: "per person (without flight)", inclusions: ["Auckland 3N + Rotorua 2N + Queenstown 3N + Milford 1N + Christchurch 1N", "4-star hotels", "Breakfast", "Hobbiton tour", "Milford cruise", "Scenic flights", "Visa assistance", "Rental car"] },
    ],
    faqs: [
      { q: "Best time to visit New Zealand from Bangalore?", a: "December–February (New Zealand summer) is ideal for outdoor adventures. June–August (ski season) for Queenstown. March–May and September–November are pleasant shoulder seasons." },
    ],
    related: ["australia-tour-from-bangalore", "bali-tour-from-bangalore", "services/visa-agent-bangalore"],
  },

  {
    slug: "south-korea-tour-from-bangalore",
    title: "South Korea Tour Packages from Bangalore",
    type: "international",
    heroImage: "https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=1600&q=85",
    heroAlt: "South Korea Seoul Gyeongbokgung Palace tour from Bangalore",
    tagline: "Seoul, Busan, Jeju Island & K-culture — from ₹65,000",
    startPrice: "₹65,000",
    popularDuration: "7N/8D",
    tripsCount: "60+",
    visaNote: "K-ETA (electronic travel authorisation, USD 10) for Indians",
    highlights: [
      { place: "Seoul", desc: "Gyeongbokgung Palace, Bukchon Hanok Village, Myeongdong shopping & Gangnam." },
      { place: "Jeju Island", desc: "Hallasan volcano, Manjanggul lava tube, haenyeo women divers & black sand beaches." },
      { place: "Busan", desc: "Gamcheon Culture Village, Haeundae Beach, Jagalchi Fish Market." },
      { place: "DMZ (Demilitarised Zone)", desc: "Joint Security Area — the most heavily armed border in the world." },
      { place: "Nami Island", desc: "Beautiful leaf-lined lanes — famous from Korean drama Winter Sonata." },
      { place: "K-Pop Experience", desc: "SMTOWN, BigHit Entertainment, fan shops & recording studio tours." },
    ],
    packages: [
      { name: "Korea Classic", duration: "7N/8D", price: "₹65,000", priceNote: "per person (without flight)", inclusions: ["Seoul 4N + Busan 2N + Jeju 1N", "4-star hotels", "Daily breakfast", "All city tours", "DMZ tour", "K-ETA assistance", "Transfers"] },
      { name: "Korea with Flights", duration: "7N/8D", price: "₹95,000", priceNote: "per person, incl. BLR–ICN flights", inclusions: ["Bangalore–Seoul–Bangalore", "Full itinerary", "4-star hotels", "Breakfast", "K-ETA", "Transfers"], tag: "Most Popular" },
    ],
    faqs: [
      { q: "Best time to visit South Korea from Bangalore?", a: "March–May (cherry blossom) and September–November (autumn foliage) are the most beautiful. June–August is hot and humid. December–February is cold but clear." },
    ],
    related: ["japan-tour-from-bangalore", "singapore-tour-from-bangalore", "bali-tour-from-bangalore"],
  },

  {
    slug: "georgia-armenia-tour-from-bangalore",
    title: "Georgia & Armenia Tour Packages from Bangalore",
    type: "international",
    heroImage: "https://images.unsplash.com/photo-1590069261209-f8e9b8642343?w=1600&q=85",
    heroAlt: "Georgia Tbilisi Armenia Yerevan tour from Bangalore",
    tagline: "Tbilisi, Kazbegi, Yerevan & Khor Virap — hidden gems from ₹45,000",
    startPrice: "₹45,000",
    popularDuration: "7N/8D",
    tripsCount: "80+",
    visaNote: "Georgia & Armenia: visa-free for Indians",
    highlights: [
      { place: "Tbilisi Old Town", desc: "Sulphur baths, cable car to Narikala fortress, colourful balconies & vine streets." },
      { place: "Kazbegi (Stepantsminda)", desc: "Gergeti Trinity Church above the clouds with Mount Kazbek backdrop." },
      { place: "Batumi", desc: "Black Sea beach resort with Alphabet Tower, botanical garden & casinos." },
      { place: "Yerevan, Armenia", desc: "Cascade monument, Vernissage market, Republic Square & brandy factory." },
      { place: "Khor Virap", desc: "Monastery at the foot of Mount Ararat — Armenia's most iconic landscape." },
      { place: "Vardzia Cave City", desc: "12th-century cave monastery carved into the cliffside in southern Georgia." },
    ],
    packages: [
      { name: "Georgia Explorer", duration: "6N/7D", price: "₹45,000", priceNote: "per person (without flight)", inclusions: ["Tbilisi 3N + Kazbegi 1N + Batumi 2N", "3-star hotels", "Daily breakfast", "Kazbegi jeep tour", "Old Tbilisi walk", "Transfers"] },
      { name: "Georgia + Armenia", duration: "9N/10D", price: "₹65,000", priceNote: "per person (without flight)", inclusions: ["Tbilisi 4N + Kazbegi 1N + Yerevan 3N + Khor Virap", "4-star hotels", "Breakfast & dinner", "All tours", "Cross-border transfers"], tag: "Most Popular" },
    ],
    faqs: [
      { q: "Do Indians need a visa for Georgia and Armenia?", a: "No — Indian passport holders get visa-free entry to both Georgia and Armenia. Just show your Indian passport at immigration." },
    ],
    related: ["turkey-tour-from-bangalore", "europe-tour-from-bangalore", "dubai-tour-from-bangalore"],
  },

  {
    slug: "uzbekistan-tour-from-bangalore",
    title: "Uzbekistan Tour Packages from Bangalore",
    type: "international",
    heroImage: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1600&q=85",
    heroAlt: "Uzbekistan Samarkand Registan Square tour from Bangalore",
    tagline: "Samarkand, Bukhara, Khiva & the Silk Road — from ₹48,000",
    startPrice: "₹48,000",
    popularDuration: "7N/8D",
    tripsCount: "50+",
    visaNote: "e-Visa required (free, 3 working days)",
    highlights: [
      { place: "Samarkand", desc: "Registan Square — three magnificent Timurid madrasahs, Shah-i-Zinda & Bibi-Khanym." },
      { place: "Bukhara", desc: "Living Silk Road city — Ark Fortress, Kalon Minaret, trading domes." },
      { place: "Khiva (Ichon-Qala)", desc: "UNESCO Heritage walled city — perfectly preserved medieval Islamic architecture." },
      { place: "Tashkent", desc: "Chorsu Bazaar, Hazrat Imam complex, Amir Temur Square & subway art." },
      { place: "Fergana Valley", desc: "Traditional silk weaving, ceramics workshops & mountain villages." },
      { place: "Nurata", desc: "Desert oasis — traditional yurt stays under the Kyzylkum stars." },
    ],
    packages: [
      { name: "Uzbekistan Highlights", duration: "7N/8D", price: "₹48,000", priceNote: "per person (without flight)", inclusions: ["Tashkent 2N + Samarkand 2N + Bukhara 2N + Khiva 1N", "3-star hotels", "Daily breakfast", "All Registan visits", "Silk Road museums", "e-Visa", "Transfers"] },
      { name: "Uzbekistan with Flight", duration: "8N/9D", price: "₹68,000", priceNote: "per person, incl. BLR–TAS flights", inclusions: ["Bangalore–Tashkent–Bangalore", "Full Silk Road circuit", "4-star hotels", "All meals", "e-Visa", "Transfers"], tag: "Most Popular" },
    ],
    faqs: [
      { q: "Do Indians need a visa for Uzbekistan?", a: "Indian passport holders need an e-Visa which is free and takes about 3 working days. We assist with all e-Visa applications." },
    ],
    related: ["turkey-tour-from-bangalore", "europe-tour-from-bangalore", "georgia-armenia-tour-from-bangalore"],
  },
];

export const allDestinations: Destination[] = D;

export function getDestination(slug: string): Destination | undefined {
  return D.find((d) => d.slug === slug);
}

export function getAllSlugs(): string[] {
  return D.map((d) => d.slug);
}
